name: build

on: [push, pull_request]

permissions:
  contents: read

jobs:
  msys2-gcc:
    runs-on: windows-latest

    strategy:
      matrix:
        build_configuration: [Debug, Release]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: mingw32
          pacboy: >-
            toolchain:p
            cmake:p
            ninja:p

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        shell: msys2 {0}
        run: |
          cmake -G "Ninja" -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_configuration }}
          cmake --build build

      - name: Create archive
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          7z a msys2-gcc_${{ matrix.build_configuration }}.zip build\Custom-SmoothDfA.auf README.md

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: msys2-gcc
          path: |
            msys2-gcc_${{ matrix.build_configuration }}.zip

  msys2-clang:
    runs-on: windows-latest

    env:
      CC: clang
      CXX: clang++

    strategy:
      matrix:
        build_configuration: [Debug, Release]
        mimalloc: [on, off]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: mingw32
          pacboy: >-
            clang:p
            compiler-rt:p
            llvm:p
            crt-git:p
            headers-git:p
            libc++:p
            libc++abi:p
            libunwind:p
            libmangle-git:p
            libwinpthread-git:p
            winpthreads-git:p
            make:p
            openmp:p
            pkgconf:p
            tools-git:p
            winstorecompat-git:p
            cmake:p
            ninja:p

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        shell: msys2 {0}
        run: |
          cmake -G "Ninja" -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_configuration }} -DCMAKE_C_FLAGS="--rtlib=compiler-rt -unwindlib=libunwind" -DCMAKE_CXX_FLAGS="-stdlib=libc++" -DMIMALLOC=${{ matrix.mimalloc }}
          cmake --build build

      - name: Create archive
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          7z a msys2-clang_${{ matrix.build_configuration }}_mimalloc-${{ matrix.mimalloc }}.zip build\Custom-SmoothDfA.auf README.md

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: msys2-clang
          path: |
            msys2-clang_${{ matrix.build_configuration }}_mimalloc-${{ matrix.mimalloc }}.zip

  #  msvc-cl:
  #    runs-on: windows-latest
  #
  #    strategy:
  #      matrix:
  #        build_configuration: [Debug, Release]
  #
  #    steps:
  #      - uses: actions/checkout@v3
  #        with:
  #          fetch-depth: 0
  #          submodules: true
  #
  #      - name: Enable Developer Command Prompt
  #        uses: ilammy/msvc-dev-cmd@v1.10.0
  #        with:
  #          arch: win32
  #
  #      - name: Build
  #        working-directory: ${{env.GITHUB_WORKSPACE}}
  #        run: |
  #          cmake -G "Ninja" -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_configuration }} -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe"
  #          cmake --build build
  #
  #      - name: Create archive
  #        working-directory: ${{env.GITHUB_WORKSPACE}}
  #        run: |
  #          7z a msvc-cl_${{ matrix.build_configuration }}.zip build\Custom-SmoothDfA.auf README.md
  #
  #      - name: Upload artifact
  #        uses: actions/upload-artifact@v3
  #        with:
  #          name: msvc-cl
  #          path: |
  #            msvc-cl_${{ matrix.build_configuration }}.zip

  msvc-clang:
    runs-on: windows-latest

    strategy:
      matrix:
        build_configuration: [ Debug, Release ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.10.0
        with:
          arch: win32

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          cmake -G "Ninja" -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_configuration }} -DCMAKE_C_COMPILER:FILEPATH="C:/PROGRAM FILES/MICROSOFT VISUAL STUDIO/2022/ENTERPRISE/VC/Tools/Llvm/bin/clang.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/PROGRAM FILES/MICROSOFT VISUAL STUDIO/2022/ENTERPRISE/VC/Tools/Llvm/bin/clang++.exe" -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe"
          cmake --build build

      - name: Create archive
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          7z a msvc-clang_${{ matrix.build_configuration }}.zip build\Custom-SmoothDfA.auf README.md

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: msvc-clang
          path: |
            msvc-clang_${{ matrix.build_configuration }}.zip
