name: MSBuild

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        BUILD_CONFIGURATION: [Debug, Release]

    steps:
      - uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup ninja
        run: |
          choco install ninja -y

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.10.0

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          cmake -G "Ninja" -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_CONFIGURATION }}
          cmake --build build
