name: MSBuild

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        build_configuration: [Debug, Release]

    steps:
      - uses: actions/checkout@v3

      - name: Setup ninja
        run: |
          choco install ninja -y

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.10.0
        with:
          arch: win32

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          cmake -G "Ninja" -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_configuration }}
          cmake --build build
